estrezzaprj/carts/urls.py
from django . urls import path
from .  import views

urlpatterns = [
    path('',views.cart, name='cart'),
    path('add_cart/<int:product_id>/',views.add_cart, name='add_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/',views.remove_cart, name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/',views.remove_cart_item, name='remove_cart_item'),
    path('checkout/', views.checkout, name="checkout")
    
]

estrezzaprj/estrezzaprj/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home, name='home'),
    path('store/', include('store.urls')),
    path('accounts/', include('accounts.urls')),
    path('adminside/', include('adminside.urls')),
    path('cart/', include('carts.urls')),
   
    # Orders:
    path('orders/', include('orders.urls')),
    
] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

estrezzaprj/store/urls.py
from django.urls import path
from . import views



urlpatterns = [
    path('', views.store, name='store'),
    
    # for category wise urls like '...../shirts'
    path('category/<slug:category_slug>/', views.store, name='products_by_category'),
    
    # for individual product page
    path('category/<slug:category_slug>/<slug:product_slug>/', views.product_detail, name='product_detail'), 
    
    # for search bar
    path('search/', views.search, name= "search"),
]

estrezzaprj/carts/models.py
from django.db import models
from store.models import Product,Variation
from accounts.models import *

# Create your models here.

class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank = True)
    date_added = models.DateTimeField(auto_now_add=True)
    
    
    def __str__(self):
        return self.cart_id
    
class CartItem(models.Model):
    
    user = models.ForeignKey(Account, on_delete= models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variations = models.ManyToManyField(Variation, blank=True) #we can have same product with different variations in cart, so using many to many field to handle it
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, null= True)
    quantity = models.IntegerField()
    is_active = models.BooleanField(default=True)
    
    
    def sub_total(self):
        return self.product.price * self.quantity
    

    def __unicode__(self):
        return self.product
    

estrezzaprj/store/models.py
from django.db import models
from category.models import Category
from django.urls import reverse
from autoslug import AutoSlugField
# Create your models here.

class Product(models.Model):
    product_name = models.CharField(max_length=200, unique = True)
    slug = AutoSlugField(populate_from='product_name',max_length=100, unique=True,null=True, default='')
    description = models.TextField(max_length=500, blank=True)
    price = models.IntegerField()
    images = models.ImageField(upload_to='photos/products')
    stock = models.IntegerField()
    
    is_available = models.BooleanField(default=True)
   
    # foreign key with category
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    
    created_date = models.DateTimeField(auto_now_add = True)
    modified_date = models.DateTimeField(auto_now= True)
    
    def get_url(self):
        return reverse('product_detail', args= [self.category.slug, self.slug])
    
    
    def __str__(self):
        return self.product_name
    
# manager allow you to modify queryset
class VariationManager(models.Manager):
    def colors(self):
        return super(VariationManager,self).filter(variation_category= 'color', is_active= True) # this will return color
    
    def sizes(self):
        return super(VariationManager,self).filter(variation_category= 'size', is_active= True) # this will return sizes
  
# variation category choices, this will go to the models
variation_category_choice = (
    ('color', 'color'),
    ('size', 'size'),

)
# 
    
class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation_category = models.CharField(max_length=100, choices=variation_category_choice) #its in dropdown as its given in choices
    variation_value = models.CharField(max_length=100)
    # 
    #  if we want to disable any variation values , we can do that using is_active:
    is_active = models.BooleanField(default=True)
    # 
    created_date = models.DateTimeField(auto_now=True)
    
    objects= VariationManager()
    
    # instead of string representation we are using unicode, because product is not a string but a model  
    def __str__(self):
        return self.variation_value
    
    '''
    you can also write it as :
    
    def __str__(self):
    return repr(self.product)
    
    # repr returns the string representation of object
    '''

estrezzaprj/carts/views.py
from django.shortcuts import render,redirect,get_object_or_404,HttpResponse
from store.models import Product,Variation
from . models import Cart, CartItem
from django.contrib.auth.decorators import login_required
# for obkect not found to use in cart
from django.core.exceptions import ObjectDoesNotExist


# Create your views here.


# we can make a function as a private function by adding a undersquare before it
def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart

def add_cart(request, product_id):
    
    current_user  = request.user
    product = Product.objects.get(id = product_id) #it will get the product here
    
    # if user authenticated 
    if current_user.is_authenticated:
        
        product_variation = []
        
        # we set the variants in form so lets check it:
        if request.method == 'POST':
            # varients:
            for item in request.POST:
                key = item
                value = request.POST[key]
                # 
                try:
                    # using i exact will ignore if the key is caps or in small letter
                    variation = Variation.objects.get(product=product, variation_category__iexact = key, variation_value__iexact = value)
                    product_variation.append(variation)
                
                except:
                    pass
            

        
        # is_cart_item_exits returns a true or false value, by checking if the same cart item is there or not
        is_cart_item_exists = CartItem.objects.filter(product=product, user=current_user).exists()
        if is_cart_item_exists:
            #  create is used here so that same products with different variations will be added seperately in cart
            cart_item = CartItem.objects.filter(product=product, user= current_user)

            ex_var_list = []
            id = []

            for item in cart_item:
                existing_variation = item.variations.all()
                ex_var_list.append(list(existing_variation))
                id.append(item.id)
            
            if product_variation in ex_var_list:
                # increasing cart item quantity
                index = ex_var_list.index(product_variation)
                item_id = id[index]
                item = CartItem.objects.get(product=product, id=item_id)
                item.quantity += 1
                item.save()
            else:
                # we will create a new cart item with quantity 1
                item = CartItem.objects.create(product=product, quantity=1, user=current_user)
                if len(product_variation) > 0:
                    item.variations.clear()
                    item.variations.add(*product_variation)    
                item.save()
        
        else:
            cart_item = CartItem.objects.create(
                product = product,
                quantity = 1,
                user = current_user,
            )
            if len(product_variation) > 0:
                cart_item.variations.clear()
                cart_item.variations.add(*product_variation)
            cart_item.save()
        
        return redirect('cart')
    
    # 
    # if user is not authenticated
    else:
        
        product_variation = []
        
        # we set the variants in form so lets check it:
        if request.method == 'POST':
            # varients:
            for item in request.POST:
                key = item
                value = request.POST[key]
                # 
                try:
                    # using i exact will ignore if the key is caps or in small letter
                    variation = Variation.objects.get(product=product, variation_category__iexact = key, variation_value__iexact = value)
                    product_variation.append(variation)
                
                except:
                    pass
            
    
        
        try:
            cart = Cart.objects.get(cart_id = _cart_id(request)) #get the cart using _cart_id from session

        except Cart.DoesNotExist:
            cart = Cart.objects.create(
                cart_id = _cart_id(request)
            )
        cart.save()
        
        # is_cart_item_exits returns a true or false value, by checking if the same cart item is there or not
        is_cart_item_exists = CartItem.objects.filter(product=product, cart=cart).exists()
        if is_cart_item_exists:
            #  create is used here so that same products with different variations will be added seperately in cart
            cart_item = CartItem.objects.filter(product=product, cart=cart)
            
            # existing variations -> database
            # current variation -> product_variation list
            # item id -> database
            
            ex_var_list = []
            id = []
            for item in cart_item:
                existing_variation = item.variations.all()
                ex_var_list.append(list(existing_variation))
                id.append(item.id)
                
            print(ex_var_list)
            
            if product_variation in ex_var_list:
                # increasing cart item quantity
                index = ex_var_list.index(product_variation)
                item_id = id[index]
                item = CartItem.objects.get(product=product, id=item_id)
                item.quantity += 1
                item.save()
            else:
                # we will create a new cart item with quantity 1
                item = CartItem.objects.create(product=product, quantity=1, cart=cart)
                if len(product_variation) > 0:
                    item.variations.clear()
                    item.variations.add(*product_variation)    
                item.save()
        
        else:
            cart_item = CartItem.objects.create(
                product = product,
                quantity = 1,
                cart = cart
            )
            if len(product_variation) > 0:
                cart_item.variations.clear()
                cart_item.variations.add(*product_variation)
            cart_item.save()
        
        return redirect('cart')
        
    
    
    
    
def cart(request, total= 0, quantity = 0, cart_items = None):
    try:
        gst = 0
        grand_total= 0
        
        # cart for logged-in users
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(user=request.user, is_active= True)
         # cart for non logged-in users
        else:
            print('not in logged in section')
            cart = Cart.objects.get(cart_id= _cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active= True)
        
            
        for cart_item in cart_items:
            total+= (cart_item.product.price * cart_item.quantity)
            quantity += cart_item.quantity
        
        gst = (18* total)/100
        grand_total = total+gst
        
    except ObjectDoesNotExist:
        pass #just ignore
    
    context = {
        'total': total,
        'quantity': quantity,
        'cart_items': cart_items,
        'gst': gst,
        'grand_total': grand_total
        
    }
        
    return render(request, 'store/cart.html', context)

# to remove the quantity of cart items in - button
def remove_cart(request, product_id, cart_item_id):
    
    
    product = get_object_or_404(Product, id=product_id)
    
    try:
        if request.user.is_authenticated:
            cart_item = CartItem.objects.get(product=product, user=request.user, id=cart_item_id)
        else:
            cart = Cart.objects.get(cart_id = _cart_id(request))
            cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
            
        if cart_item.quantity >1:
            cart_item.quantity -= 1
            cart_item.save()
        
        else:
            cart_item.delete()
    except:
        pass
    
    return redirect('cart')

# to remove the cart item row using remove button in cart
def remove_cart_item(request, product_id, cart_item_id):
    
    product = get_object_or_404(Product, id=product_id)
    
    if request.user.is_authenticated:
        cart_item = CartItem.objects.get(product=product, user=request.user, id= cart_item_id)
    else:
        cart= Cart.objects.get(cart_id = _cart_id(request))
        cart_item = CartItem.objects.get(product=product, cart=cart, id= cart_item_id)

    cart_item.delete()
    return redirect('cart')

@login_required(login_url='login')
def checkout(request, total= 0, quantity = 0, cart_items = None):
    try:
        gst = 0
        grand_total= 0
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(user=request.user, is_active= True)
         # cart for non logged-in users
        else:
            print('not in logged in section')
            cart = Cart.objects.get(cart_id= _cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active= True)
        for cart_item in cart_items:
            total+= (cart_item.product.price * cart_item.quantity)
            quantity += cart_item.quantity
        
        gst = (18* total)/100
        grand_total = total+gst
        
    except ObjectDoesNotExist:
        pass #just ignore
    
    context = {
        'total': total,
        'quantity': quantity,
        'cart_items': cart_items,
        'gst': gst,
        'grand_total': grand_total
        
    }
    
    return render(request, 'store/checkout.html',context)

estrezzaprj/store/views.py
from django.shortcuts import render, get_object_or_404,HttpResponse
from .models import Product
from category.models import Category
from carts.models import *
from carts.views import _cart_id

# for OR operations in django
from django.db.models import Q


# paginator to do the next page links:
from django.core.paginator import EmptyPage,PageNotAnInteger, Paginator



# Create your views here.


# handling paginator here
def store(request, category_slug=None):
    
    # view to set url for different categories
    
    categories = None
    products = None
    
    if category_slug != None:
        categories = get_object_or_404(Category, slug= category_slug)
        products = Product.objects.filter(category= categories, is_available= True)
        # paginator
        paginator = Paginator(products, 6)
        page = request.GET.get('page')
        paged_products = paginator.get_page(page)
        # 
        product_count = products.count()
    else:
        # saving all the items from products to list it in a dictionary
        products = Product.objects.all().filter(is_available=True).order_by('id')
        # taking product count
        
        # paginator to do the page 1,2,3...etc
        paginator = Paginator(products, 6)
        page = request.GET.get('page')
        paged_products = paginator.get_page(page)
        # 
        product_count = products.count()
        
        
    
    context = {
        'products': paged_products,
        'product_count' : product_count,
        
    }
    return render(request,'store/store.html',context)

# for product detail page(single item)

def product_detail(request, category_slug, product_slug):
    try:
        single_product = Product.objects.get(category__slug= category_slug, slug= product_slug)
        in_cart = CartItem.objects.filter(cart__cart_id= _cart_id(request), product = single_product).exists()
        
            
    except Exception as e:
        raise e
    
    context= {
        'single_product': single_product,
        'in_cart' : in_cart,
    }
    
    
    return render(request, 'store/product_detail.html',context)
    
def search(request):
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        if keyword: #if keyword is not None
            products = Product.objects.order_by('created_date').filter(Q(description__icontains= keyword) |  Q(product_name__icontains=keyword)) # whats i contains? it will look for whole description and and if it find anything same like what we are checking it will filter(we are cheaacking keyword here and also the keyword is that we are getting from url)
                                               #' Q or Queryset is the way we bring in OR operation in django' , we are importing it
            product_count = products.count()
            
    context = {
        
        'products' : products,
        'product_count' : product_count,
    }

    return render(request, 'store/store.html', context)

estrezzaprj/templates/store/cart.html
{% extends 'base.html' %}
{% load static %}

{% block custom_css %}
<!---->

<!---->
{% endblock  %}

{% block content %}


<section class="section-content padding-y bg">
    <div class="container">
    
    <!-- ============================ COMPONENT 1 ================================= -->
    
{% if not cart_items %}
<div class="text-center">
    <h3> Your Shopping Cart is Empty </h3>
    <br>
    <a href="{% url 'store' %}" class="btn" style="background-color: #070707; color: #ffffff;">Continue Shopping</a>
</div>

{% else %}

    <div class="row">
        <aside class="col-lg-9">
    <div class="card">
    <table class="table table-borderless table-shopping-cart">
    <thead class="text-muted">
    <tr class="small text-uppercase">
      <th scope="col">Product</th>
      <th scope="col" width="120">Quantity</th>
      <th scope="col" width="120">Price</th>
      <th scope="col" class="text-right" width="200"> </th>
    </tr>
    </thead>
    <tbody>
{% for cart_item in cart_items  %}

    <tr>
        <td>
            <figure class="itemside align-items-center">
                <a href="{{ cart_item.product.get_url }}"><div class="aside"><img src=" {{cart_item.product.images.url}} " class="img-sm"></div></a>
                <figcaption class="info">
                    <a href="{{ cart_item.product.get_url }}" class="title text-dark">{{cart_item.product.product_name}}</a>
                    <p class="text-muted small">
                        {% if cart_item.variations.all %}
                            {% for item in cart_item.variations.all %}
                                {{ item.variation_category | capfirst }} : {{ item.variation_value | capfirst }} <br>
                            {% endfor %}
                        {% endif %}
                        <br> </p>
                </figcaption>
            </figure>
        </td>
        <td> 
            <!-- col.// -->
                        <div class="col"> 
                            <div class="input-group input-spinner">
                                <div class="input-group-prepend">
                                <a href="{% url 'remove_cart' cart_item.product.id cart_item.id %}" class="btn btn-light" type="button" id="button-minus"> <i class="fa fa-minus"></i> </a>
                                </div>
                                <input readonly class="form-control"  value="{{cart_item.quantity}}">
                                <div class="input-group-append"> 
                                    <form action="{% url 'add_cart' cart_item.product.id %}" method="POST">
                                        {% csrf_token %}
                                        {% for item in cart_item.variations.all %}
                                            <input type="hidden" name="{{ item.variation_category | lower }}" value="{{ item.variation_value | capfirst }}">
                                        {% endfor %}
                                        <button class="btn btn-light" type="submit" id="button-plus"> <i class="fa fa-plus"></i> </button>
                                    </form>
                                </div>
                            </div> <!-- input-group.// -->
                        </div> <!-- col.// -->
        </td>
        <td> 
            <div class="price-wrap"> 
                <var class="price">₹ {{ cart_item.sub_total }}</var> 
                <small class="text-muted">₹ {{ cart_item.product.price }}</small> 
            </div> <!-- price-wrap .// -->
        </td>
        <td class="text-right"> 
        <a href="{% url 'remove_cart_item' cart_item.product.id cart_item.id %}" onclick="return confirm('Are you sure you want to delete this item?')" class="btn btn-danger"> Remove</a>
        </td>
    </tr>

    {% endfor %}
    
    </tbody>
    </table>
    </div> <!-- card.// -->
    
        </aside> <!-- col.// -->
        <aside class="col-lg-3">
    
            <div class="card">
            <div class="card-body">
                <dl class="dlist-align">
                  <dt>Total price:</dt>
                  <dd class="text-right">₹ {{total}}</dd>
                </dl>
                <dl class="dlist-align">
                  <dt>GST:</dt>
                  <dd class="text-right">₹ {{gst}} </dd>
                </dl>
                <dl class="dlist-align">
                  <dt>Total:</dt>
                  <dd class="text-right text-dark b"><strong>₹ {{grand_total}}</strong></dd>
                </dl>
                <hr>
                <p class="text-center mb-3">
                    <img src="{% static './images/misc/payments.png' %}" height="26">
                </p>
                <a href="{% url 'checkout' %}" class="btn btn-block" style="background-color: #070707; color: #ffffff;"> Checkout </a>
                <a href="{% url 'store' %}" class="btn btn-light btn-block">Continue Shopping</a>
            </div> <!-- card-body.// -->
            </div> <!-- card.// -->
    
    </aside> <!-- col.// -->
    
    
    </div> <!-- row.// -->
    <!-- ============================ COMPONENT 1 END .// ================================= -->
    
    {% endif %}

    </div> <!-- container .//  -->
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->



{% endblock  %}

estrezzaprj/templates/store/product_detail.html
{% extends 'base.html' %}
{% load static %}

{% block custom_css %}
<link rel="stylesheet" href="{% static 'css/store/product_detail.css' %}">

{% endblock %}

{% block content %}



<section class="section-content padding-y bg">
    <div class="container">
    
    <!-- ============================ COMPONENT 1 ================================= -->
    <div class="card">
        <div class="row no-gutters">
            <aside class="col-md-6">
    <article class="gallery-wrap"> 
        <div class="img-big-wrap">
           <a href="#"><img src="{{single_product.images.url}}" class="prodcut_img"></a>
        </div> <!-- img-big-wrap.// -->
        
    </article> <!-- gallery-wrap .end// -->
            </aside>
            <main class="col-md-6 border-left">

  <!-- using these in form for varients-->

  <form action='{% url 'add_cart' single_product.id %}' method ="POST">
    
    {% csrf_token %}

      <article class="content-body">
      
      <h2 class="title">{{single_product.product_name}}</h2>
      
      <div class="mb-3"> 
          <var class="price h4">₹{{single_product.price}}</var> 
      </div> 
      
      <p>{{single_product.description}}</p>
      
      
      <hr>
          <div class="row">
              <div class="item-option-select">
                  <h6>Choose Color</h6>
                  <select name="color" id="" class="form-control" required> 
                    <option values="" disabled selected>Select</option>
                    {% for i in single_product.variation_set.colors  %} <!-- set.colors: colors is a function from variation manager (we defined it in store/models)-->
                        <option value="{{ i.variation_value | lower }}">{{ i.variation_value | capfirst }}</option>
                    {% endfor %}
                  </select> 
              </div>
          </div> <!-- row.// -->
          <div class="row">
              <div class="item-option-select">
                  <h6>Select Size</h6>
                  <select name="size" id="" class="form-control">
                    <option values="" disabled selected>Select</option>
                    {% for i in single_product.variation_set.sizes  %} <!-- set.colors: colors is a function from variation manager (we defined it in store/models)-->
                        <option value="{{ i.variation_value | lower }}">{{ i.variation_value | capfirst }}</option>
                    {% endfor %}
                    
                  </select> 
                  
              </div>
          </div> <!-- row.// -->
          <hr>
          {% if single_product.stock < 1 %}
            <h6 style="color:rgb(163, 0, 0)">Product Out Of Stock !!</h6>
          {% else %}
            <button type="submit" class="btn add-to-cart-button"> <span class="text">Add to cart</span> <i class="fa fa-shopping-cart" style="color: #ffffff;"></i>  </button>
          {% endif %}
      </article> <!-- product-info-aside .// -->
  </form>

            </main> <!-- col.// -->
        </div> <!-- row.// -->
    </div> <!-- card.// -->
    <!-- ============================ COMPONENT 1 END .// ================================= -->
    
    <br>
    
    <div class="row">
                <div class="col-md-9">
    
        <header class="section-heading">
            <h3>Customer Reviews </h3>  
            
        </header>
    
        <article class="box mb-3">
            <div class="icontext w-100">
                <img src="{% static './images/avatars/rabi_avatar.jpg' %}" class="img-xs icon rounded-circle">
                <div class="text">
                    <span class="date text-muted float-md-right">21-08-2023</span>  
                    <h6 class="mb-1">Rabi / Review keng! </h6>
                    
                </div>
            </div> <!-- icontext.// -->
            <div class="mt-3">
                <p>
                    Mone poli sannam ! Venel vedicha mathi
                </p>	
            </div>
        </article>
    
        
    
        </div> <!-- col.// -->
    </div> <!-- row.// -->
    
    
    </div> <!-- container .//  -->
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->


{% endblock content %}