estrezzaprj/adminside/urls.py
from django.urls import path
from . import views


urlpatterns = [
    # login and logout
    path('', views.admin_login, name= 'admin_login'),
    path('admin_logout/', views.admin_logout, name='admin_logout'),
    
    # dashboard
    path('admin_dashboard/', views.admin_dashboard, name= 'admin_dashboard'),
    
    # listing users, products, categories
    path('admin_user/', views.admin_user, name= 'admin_user'),
    path('admin_product/', views.admin_product, name= 'admin_product'),
    path('admin_category/', views.admin_category, name= 'admin_category'),
    
    # user actions
    path('block_user/<int:id>/', views.block_user, name= 'block_user'),
    path('unblock_user/<int:id>/', views.unblock_user, name= 'unblock_user'),
    
    # categories actions
    path('add_category/', views.add_category, name= 'add_category'),
    path('delete_category/<int:id>/', views.delete_category, name= 'delete_category'),
    path('edit_category/<int:id>/', views.edit_category, name= 'edit_category'),
    
    # products actions
    path('add_product/', views.add_product, name= 'add_product'),
    path('delete_product/<int:id>/', views.delete_product, name= 'delete_product'),
    path('edit_product/<int:id>/', views.edit_product, name= 'edit_product'),
    

    


   
] 

estrezzaprj/carts/urls.py
from django . urls import path
from .  import views

urlpatterns = [
    path('',views.cart, name='cart'),
    path('add_cart/<int:product_id>/',views.add_cart, name='add_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/',views.remove_cart, name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/',views.remove_cart_item, name='remove_cart_item'),
    path('checkout/', views.checkout, name="checkout")
    
]

estrezzaprj/estrezzaprj/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home, name='home'),
    path('store/', include('store.urls')),
    path('accounts/', include('accounts.urls')),
    path('adminside/', include('adminside.urls')),
    path('cart/', include('carts.urls')),
   
    # Orders:
    path('orders/', include('orders.urls')),
    
] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

estrezzaprj/adminside/models.py
from django.db import models

# Create your models here.

estrezzaprj/orders/models.py
from django.db import models
from accounts.models import *
from store.models import *



# Create your models here.

class Payment(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    payment_id = models.CharField(max_length=100)
    payment_method = models.CharField(max_length=100)
    amount_paid = models.CharField(max_length=100) #total amount paid
    status = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    
    
    def __str__(self):
        return self.payment_id
    
class Order(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Completed', 'Completed'),
        ('Cancelled', 'Cancelled'),
    )
    
    user = models.ForeignKey(Account, on_delete=models.SET_NULL, null=True)
    payment = models.ForeignKey(Payment, on_delete=models.SET_NULL, blank=True, null=True)
    order_number = models.CharField(max_length=20)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.CharField(max_length=15)
    email = models.EmailField(max_length=50)
    address_line_1 = models.CharField(max_length=50)
    address_line_2 = models.CharField(max_length=50, blank=True)
    country = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    order_note = models.CharField(max_length=100, blank=True)
    order_total = models.FloatField()
    tax = models.FloatField()
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    ip = models.CharField(blank=True, max_length=20)
    is_ordered = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    
    
    def full_name(self):
        return f'{self.first_name} {self.last_name}'
    
    def full_address(self):
        return f'{self.address_line_1}, {self.address_line_2}'
    
    def __str__(self):
        return self.first_name
    
    
class OrderProduct(models.Model):
    # foreign keys:
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    payment = models.ForeignKey(Payment, on_delete=models.SET_NULL, blank=True, null=True)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variations = models.ManyToManyField(Variation, blank = True)

    quantity = models.IntegerField()
    product_price = models.FloatField()
    ordered = models.BooleanField(default=False)
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    
    def __str__(self):
        return self.product.product_name
    

estrezzaprj/store/models.py
from django.db import models
from category.models import Category
from django.urls import reverse
from autoslug import AutoSlugField
# Create your models here.

class Product(models.Model):
    product_name = models.CharField(max_length=200, unique = True)
    slug = AutoSlugField(populate_from='product_name',max_length=100, unique=True,null=True, default='')
    description = models.TextField(max_length=500, blank=True)
    price = models.IntegerField()
    images = models.ImageField(upload_to='photos/products')
    stock = models.IntegerField()
    
    is_available = models.BooleanField(default=True)
   
    # foreign key with category
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    
    created_date = models.DateTimeField(auto_now_add = True)
    modified_date = models.DateTimeField(auto_now= True)
    
    def get_url(self):
        return reverse('product_detail', args= [self.category.slug, self.slug])
    
    
    def __str__(self):
        return self.product_name
    
# manager allow you to modify queryset
class VariationManager(models.Manager):
    def colors(self):
        return super(VariationManager,self).filter(variation_category= 'color', is_active= True) # this will return color
    
    def sizes(self):
        return super(VariationManager,self).filter(variation_category= 'size', is_active= True) # this will return sizes
  
# variation category choices, this will go to the models
variation_category_choice = (
    ('color', 'color'),
    ('size', 'size'),

)
# 
    
class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation_category = models.CharField(max_length=100, choices=variation_category_choice) #its in dropdown as its given in choices
    variation_value = models.CharField(max_length=100)
    # 
    #  if we want to disable any variation values , we can do that using is_active:
    is_active = models.BooleanField(default=True)
    # 
    created_date = models.DateTimeField(auto_now=True)
    
    objects= VariationManager()
    
    # instead of string representation we are using unicode, because product is not a string but a model  
    def __str__(self):
        return self.variation_value
    
    '''
    you can also write it as :
    
    def __str__(self):
    return repr(self.product)
    
    # repr returns the string representation of object
    '''

estrezzaprj/adminside/forms.py
from django import forms
# importing category model from category app
from  category.models import Category
from store.models import Product
#  for auto populating slug field
from django.utils.text import slugify

class CategoryForm(forms.ModelForm):
    
    class Meta:
        model = Category
        exclude = ['slug']
        fields = ['category_name','description','cat_image']
   
    def __init__(self,*args, **kwargs):
        super(CategoryForm, self).__init__(*args, **kwargs)
        
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'
            self.fields[field].widget.attrs['placeholder'] = f'{field.replace("_", " ").capitalize()}'
            self.fields[field].widget.attrs['style'] = 'border: none; border-radius: 30px; font-size: 15px; height: 45px; outline: none; color: black; background: rgba(255, 255, 255, 0.1); cursor: pointer; transition: 0.3s; margin-top: 10px; color:#ffffff; text-align: center;'
            self.fields[field].widget.attrs['onfocus'] = 'this.style.outline = "1px solid #F3F4F7"; this.style.transform = "scale(1.04)";'
            self.fields[field].widget.attrs['onblur'] = 'this.style.outline = ""; this.style.transform = ""; this.style.boxShadow = "";'

            
class ProductForm(forms.ModelForm):
    
    class Meta:
        model = Product
        fields = ['product_name','description','price','images','stock']
        
        
    def __init__(self,*args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'
            self.fields[field].widget.attrs['placeholder'] = f'{field.replace("_", " ").capitalize()}'
            self.fields[field].widget.attrs['style'] = 'border: none; border-radius: 30px; font-size: 15px; height: 45px; outline: none; color: black; background: rgba(255, 255, 255, 0.1); cursor: pointer; transition: 0.3s; margin-top: 10px; color:#ffffff; text-align: center;'
            
 
    

estrezzaprj/adminside/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from .forms import *
from category.models import Category
from accounts.models import Account
from store.models import Product
from django.contrib import messages

# Create your views here.

def admin_login(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        user = authenticate(request, email=email, password=password)
        if user is not None and user.is_superadmin:
            login(request, user)
            return redirect('admin_dashboard')  # Replace 'admin_dashboard' with the appropriate URL for your admin dashboard
        else:
            messages.warning(request,'Invalid Credentials')
            return redirect('admin_login')
    else:
        message = ''

    context = {'message': message}
    return render(request, 'adminside/admin_login.html', context)


def admin_logout(request):
    logout(request)
    return redirect('admin_login')  # Redirect to the admin login page after logging out

@login_required(login_url='admin_login')
def block_user(request,id):
    account = Account.objects.get(pk = id)
    account.is_active = False
    account.save()
    return redirect('admin_user')

@login_required(login_url='admin_login')
def unblock_user(request,id):
    account = Account.objects.get(pk = id)
    account.is_active = True
    account.save()
    return redirect('admin_user')


# dashboard:
@login_required(login_url='admin_login')
def admin_dashboard(request):
    return render(request, 'adminside/admin_dashboard.html')

# list users, categories and products:
@login_required(login_url='admin_login')
def admin_user(request):
    account_object= Account.objects.all
    context ={
        'account_object': account_object
    }
    return render(request, 'adminside/admin_user.html',context)

@login_required(login_url='admin_login')
def admin_product(request):
    product_object = Product.objects.all
    context = {
        'product_object': product_object
    }
    return render(request, 'adminside/admin_product.html',context)

@login_required(login_url='admin_login')
def admin_category(request):
    category_object = Category.objects.all
    context = {
        'category_object': category_object
    }
    return render(request, 'adminside/admin_category.html', context)


# category actions: add,delete,edit
@login_required(login_url='admin_login')
def add_category(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST, request.FILES)
        if form.is_valid():
            category = form.save(commit=False)
            category.slug = slugify(category.category_name)
            category.save()
            messages.success(request, 'Category added successfuly.')
            return redirect('admin_category')
        
    else:
        form = CategoryForm()
    context = {
        'form': form
    }
        
    
    return render(request, 'adminside/add_category.html',context )


@login_required(login_url='admin_login')
def delete_category(request,id):
    category = Category.objects.get(pk=id)
    category.delete()
    messages.warning(request, 'Category deleted')
    return redirect('admin_category')

@login_required(login_url='admin_login')
def edit_category(request, id):
    category = get_object_or_404(Category, pk=id)
    if request.method == "POST":
        form = CategoryForm(request.POST, request.FILES, instance=category)
        if form.is_valid():
            form.save()
            messages.success(request, 'Category edited successfully')
            return redirect('admin_category')
    else:
        form = CategoryForm(instance=category)

    context = {
        "form": form
    }
    return render(request, 'adminside/edit_category.html', context)

# products actions: (add,delete,edit):
@login_required(login_url='admin_login')
def add_product(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save(commit=False)
            product.slug = slugify(product.product_name)
            product.category_id = request.POST.get('category')  # Retrieve the selected category ID   
            product.save()
            messages.success(request, 'Product added successfuly.')
            return redirect('admin_product')  # Redirect to the admin product page after saving

    else:
        form = ProductForm()
        categories = Category.objects.all
    context = {
        'form': form,
        'categories': categories,
    }
    return render(request, 'adminside/add_product.html', context)

@login_required(login_url='admin_login')
def delete_product(request,id):
    product = Product.objects.get(pk=id)
    product.delete()
    messages.warning(request, 'Product deleted')
    return redirect('admin_product')

@login_required(login_url='admin_login')
def edit_product(request, id):
    product = get_object_or_404(Product, pk=id)
    if request.method == "POST":
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            messages.success(request, 'Product edited successfully')
            return redirect('admin_product')
    else:
        form = ProductForm(instance=product)

    context = {
        "form": form
    }
    return render(request, 'adminside/edit_product.html', context)

estrezzaprj/templates/adminside/add_category.html
{% extends 'adminside/admin_base.html' %}
{% load static %}

{% block custom_css_admin %}

<link rel="stylesheet" href="{% static 'css/accounts/register.css' %}">

{% endblock  %}
    {% block admin_page_contents %}
    
    
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->

    <i class="fa fa-arrow-left" aria-hidden="true"></i><span style="color: #333333;"> Redirect back to view Categories?</span>
    <br>
    <a href="{% url 'admin_category' %}" style="color: #070707; font-weight: 700;">Click here</a>
    
    <br>

    
        <div class="box new1">
            <div class="container login-form new2" style="width: 50%; align-items: center; color: #ffffff;">
    
              
                <div class="top new3">
                    <div class="logo new4">
                        <img src="{% static 'images/logo white for login.png' %}" alt="Logo">
                    </div>
                    <h3>Got New Categories?</h3>
                    <br>
             
                    
                </div>
    
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="input-field new5">
                        Category Name :
                        {{form.category_name}}
                    </div>
    
                    <div class="input-field new5">
                        <p style="color: rgb(196, 3, 3);">*Slug : AutoGenerated</p>

                    </div>
                        Description :
                    <div class="input-field new5">
                        {{form.description}}
                    </div>
                        Category Image :
                    <div class="input-field new5">
                        {{form.cat_image}}
                    </div>
                    <br>
                    <p style="color: rgb(196, 3, 3);">*Make sure you didn't miss any fields</p>
    
    
                    <div class="input-field new5">
                        <input type="submit" class="submit new7" value="Add Category" id="add-category-button">
                    </div>

    {% endblock %}

estrezzaprj/templates/adminside/add_product.html
{% extends 'adminside/admin_base.html' %}
{% load static %}
{% block custom_css_admin %}

<link rel="stylesheet" href="{% static 'css/accounts/register.css' %}">

{% endblock  %}
    
{% block admin_page_contents %}
    
    
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->

    <i class="fa fa-arrow-left" aria-hidden="true"></i><span style="color: #333333;"> Redirect back to view Products?</span>
    <br>
    <a href="{% url 'admin_product' %}" style="color: #070707; font-weight: 700;">Click here</a>
    
    <br>
        <div class="box new1">
            <div class="container login-form new2" style="width: 50%; align-items: center; color: #ffffff;">
    
              
                <div class="top new3">
                    <div class="logo new4">
                        <img src="{% static 'images/logo white for login.png' %}" alt="Logo">
                    </div>
                    <br>
                    <h3>Got New Products?</h3>
                    <br>
             
                    
                </div>
    
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="input-field new5">
                        Product Name :
                        {{form.product_name}}
                    </div>
    
                    <div class="input-field new5">
                        <p style="color: rgb(196, 3, 3);">*Slug : AutoGenerated</p>
                    </div>
                        
                    <div class="input-field new5">
                        Description :
                        {{form.description}}
                    </div>
                        
                    <div class="input-field new5">
                        Price :
                        {{form.price}}
                    </div>
                    <div class="input-field new5">
                        Product Image :
                        {{form.images}}
                    </div>
                    <div class="input-field new5">
                        No. of Stocks :
                        {{form.stock}}
                    </div>
                    <br>
                    <div class="input-field new5">
                        <label for="id_category">Category:</label>
                        <select id="id_category" name="category"   style="background-color: #333333; color: #ffffff; border-radius: 10px;">
                            <option value="">Select a category</option>
                            {% for category in categories %}
                                <option value="{{ category.id }}">{{ category.category_name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    
                    <br>
                    <p style="color: rgb(196, 3, 3);">*Make sure you didn't miss any fields</p>
    
    
                    <div class="input-field new5">
                        <input type="submit" class="submit new7" value="Add Product" id="add-product-button">
                    </div>

    {% endblock %}

estrezzaprj/templates/adminside/admin_category.html
{% extends 'adminside/admin_base.html' %}
   
    {% block admin_page_contents %}

    <h2>Categories</h2>
    <p>The available categories are listed  here</p>
    <br>
    {% include 'includes/alerts.html' %}
    <br>

    <div class="container-fluid">
        <table class="table">
            <thead class="thead-dark">
              <tr>
                <th scope="col">CATEGORY NAME</th>
                <th scope="col">SLUG</th>
                <th scope="col">CATEGORY IMAGE</th>
                <th scope="col">ACTION</th>
           

              </tr>
            </thead>
            <tbody>
          {% for category_object in category_object %}

              <tr>
                <td>{{ category_object.category_name }}</td>
                <td>{{ category_object.slug }}</td>
                <td>
                  <img src="{{ category_object.cat_image.url }}" alt="" style="width: 40px; background-color: #ffffff;" >
                </td>
                <td>
                    <a href="{% url 'edit_category' category_object.id %}"><button type="button" class="btn btn-dark" style="font-size: 10px;">EDIT</button></a>
                    <a href="{% url 'delete_category' category_object.id %}"><button type="button" class="btn btn-danger" style="font-size: 10px;">DELETE</button></a>
                </td>

              </tr>

          {% endfor %}
            </tbody>
          </table>
          <a href="{% url 'add_category' %}"><button type="button" class="btn btn-dark" style="font-size: 14px;">ADD MORE CATEGORIES +</button></a>
    </div>





    {% endblock%}

estrezzaprj/templates/adminside/admin_dashboard.html
{% extends 'adminside/admin_base.html' %}
{% load static %}

{% block admin_page_contents %}

<div class="background-image" style="background-image: url('{% static 'adminside/images/dashboard.jpg' %}'); background-position: center; background-repeat: no-repeat; background-size: cover; height: 70vh;  color: rgb(176, 176, 176);">
<div class="text" style="padding: 20px;">
<h2> DASHBOARD</h2>
<p>We are updating here soon! </p>
</div>
</div>

{% endblock%}

estrezzaprj/templates/adminside/admin_login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Login - Admin</title>
        <link href="{% static 'adminside/css/styles.css' %}" rel="stylesheet" />
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    </head>

    <body style="background-image: url('{% static 'adminside/images/loginbackground.jpg' %}'); background-position: center; background-size: cover; background-repeat: no-repeat;">
        <div id="layoutAuthentication">
            <div id="layoutAuthentication_content">
                <main>
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-lg-5">
                                <div class="card shadow-lg border-0 rounded-lg mt-5">
                                    <div class="logo" style="display: flex; justify-content:center ;">
                                        <img src="{% static 'images/logo-black.png' %}" alt="Logo" style="width: 60px;" >
                                    </div>
                                    {% include 'includes/alerts.html' %}
                                    <div class="card-header"><h3 class="text-center font-weight-light my-4">Login</h3></div>
                                    <div class="card-body">
                                        <form method="POST" action="{% url 'admin_login' %}">
                                            {% csrf_token %}
                                            <div class="form-floating mb-3">
                                                <input class="form-control" id="id_email" name="email" type="email" placeholder="name@example.com" />
                                                <label for="id_email">Email address</label>
                                            </div>
                                            <div class="form-floating mb-3">
                                                <input class="form-control" id="id_password" name="password" type="password" placeholder="Password" />
                                                <label for="id_password">Password</label>
                                            </div>
                                            <div class="form-check mb-3">
                                                <input class="form-check-input" id="inputRememberPassword" type="checkbox" value="" />
                                                <label class="form-check-label" for="inputRememberPassword">Remember Password</label>
                                            </div>
                                            <div class="d-flex align-items-center justify-content-between mt-4 mb-0">
                                                <button class="btn" type="submit" style="background-color: #070707; color: #ffffff;">Login</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </main>
            </div>
            <div id="layoutAuthentication_footer">
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid px-4">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; eStrezza 2023</div>
                            <div>
                                <a href="#" style="color: #070707;">Privacy Policy</a>
                                &middot;
                                <a href="#" style="color: #070707;">Terms &amp; Conditions</a>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'adminside/js/scripts.js' %}"></script>
    </body>
</html>

estrezzaprj/templates/adminside/edit_product.html
{% extends 'adminside/admin_base.html' %}
{% load static %}
{% block custom_css_admin %}

<link rel="stylesheet" href="{% static 'css/accounts/register.css' %}">

{% endblock  %}
    
{% block admin_page_contents %}
    
    
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->

    <i class="fa fa-arrow-left" aria-hidden="true"></i><span style="color: #333333;"> Redirect back to view Products?</span>
    <br>
    <a href="{% url 'admin_product' %}" style="color: #070707; font-weight: 700;">Click here</a>
    
    <br>
        <div class="box new1">
            <div class="container login-form new2" style="width: 50%; align-items: center; color: #ffffff;">
    
              
                <div class="top new3">
                    <div class="logo new4">
                        <img src="{% static 'images/logo white for login.png' %}" alt="Logo">
                    </div>
                    <br>
                    <h3>Edit Product</h3>
                    <br>
             
                    
                </div>
    
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="input-field new5">
                        Produc Name :
                        {{form.product_name}}
                    </div>
    
                    <div class="input-field new5">
                        <p style="color: rgb(196, 3, 3);">*Slug : AutoGenerated</p>

                    </div>
                        
                    <div class="input-field new5">
                        Description :
                        {{form.description}}
                    </div>
                        
                    <div class="input-field new5">
                        Price :
                        {{form.price}}
                    </div>
                    <div class="input-field new5">
                        Product Image :
                        {{form.images}}
                    </div>
                    <div class="input-field new5">
                        No. of Stocks :
                        {{form.stock}}
                    </div>
                    <br>
                    <div class="input-field new5">
                        <label for="id_category">Category:</label>
                        <select id="id_category" name="category"   style="background-color: #333333; color: #ffffff; border-radius: 10px;">
                            <option value="">Select a category</option>
                            {% for category in categories %}
                                <option value="{{ category.id }}">{{ category.category_name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    
                    <br>
                    <p style="color: rgb(196, 3, 3);">*Make sure you didn't miss any fields</p>
    
    
                    <div class="input-field new5">
                        <input type="submit" class="submit new7" value="Edit" id="edit-product-button">
                    </div>
                    

    {% endblock %}